### ISSUE TITLE
npm test broken out of the box

### ISSUE THREAD

**Issue by kyledecot** [start-react/native-starter-kit#112]
When attempting to run `npm run test` w/ just the boilerplate code from this repo I am getting:

```
kyledecot@mbp:~/Desktop/native-starter-kit [master|✚ 2…1] $ npm test

> NativeStarterKit@6.2.0 test /Users/kyledecot/Desktop/native-starter-kit
> jest

 FAIL  __tests__/index.android.js
  ● Test suite failed to run

    Cannot find module 'ReactNativeDefaultInjection' from 'setup.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)

 FAIL  __tests__/index.ios.js
  ● Test suite failed to run

    Cannot find module 'ReactNativeDefaultInjection' from 'setup.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.5s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

#### Steps to reproduce:

1. Run steps 1 & 2 from https://github.com/start-react/native-starter-kit#2-installation
2. run `npm test`

**Comment by SupriyaKalghatgi** [comment]
#71
