### ISSUE TITLE
 ERROR  Error watching file for changes: EMFILE

### ISSUE THREAD

**Issue by myerzman** [start-react/native-starter-kit#114]
clone mostly works but with one error... 

Loading dependency graph...2017-07-12 12:11 node[12576] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-07-12 12:11 node[12576] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-07-12 12:11 node[12576] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1018:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
error Command failed with exit code 11.

**Comment by SupriyaKalghatgi** [comment]
@myerzman This is not related to Native Starter Kit
Probably with your system
Please check StackOverflow for this

**Comment by myerzman** [comment]
will do. thank you
