### ISSUE TITLE
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)/)[1];

### ISSUE THREAD

**Issue by imankitaman** [start-react/native-starter-kit#134]
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)/)[1];
                                                                                             ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (/Users/ab/Documents/ios/ios_app/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:39:94)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ab/Documents/ios/ios_app/node_modules/react-native-code-push/scripts/postlink/run.js:1:63)
    at Module._compile (module.js:641:30)
/Users/ab/Documents/ios/ios_app/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/ab/Documents/ios/ios_app/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)

**Comment by imankitaman** [comment]
resolved
