### ISSUE TITLE
Test failed 

### ISSUE THREAD

**Issue by fones** [start-react/native-starter-kit#71]
Test failed but app starts OK. Node v7.5.0.
```
Documents/Git/native-starter-kit  master ✔                                                                                                                                            10d  
▶ npm test

> NativeStarterKit@5.3.0 test /Users/fones/Documents/Git/native-starter-kit
> jest

 FAIL  __tests__/index.ios.js
  ● Test suite failed to run

    Cannot find module 'react/lib/ReactTestRenderer' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:4:18)
      at Object.<anonymous> (__tests__/index.ios.js:6:24)

 FAIL  __tests__/index.android.js
  ● Test suite failed to run

    Cannot find module 'react/lib/ReactTestRenderer' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:4:18)
      at Object.<anonymous> (__tests__/index.android.js:6:24)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        2.396s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by Tibze** [comment]
Same problem for me.
Node 7.4

**Comment by SupriyaKalghatgi** [comment]
@fones @Tibze Can you share versions of `node` and `npm` along with your `package.json`
